web:
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
        - ./web:/web
        - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
        - php
php:
    image: php:7-fpm
    volumes:
        - ./web:/web
